#5bt-test-add.jl
#testing an addition table for the 5 bit PTile.
#this vector doesn't include negative numbers, or zero or inf (which is trivial)
#note the vector looks like this:
#         [1/8]       [1/4]       [1/2]        [1]         [2]         [4]         [8]
# [00001  00010 00011 00100 00101 00110 00111 01000 01001 01010 01011 01100 01101 01110 01111]

btadd5 = [
#                | [1/8]         |               | [1/4]         |               | [1/2]         |               |  [1]          |               | [2]           |               |   [4]  |               | [8]    |
# (0 1/8) + ...
  (ooool → oooll) ▾(oooll)        (oooll → oolol) ▾(oolol)        (oolol → oolll) ▾(oolll)        (oolll → olool) ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# [1/8] + ...
  ▾(oooll)        ▾(ooloo)        ▾(oolol)        ▾(oolol)        (oolol → oolll) ▾(oolll)        (oolll → olool) ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# (1/8 1/4) + ...
  (oooll → oolol) ▾(oolol)        ▾(oolol)        ▾(oolol)        (oolol → oolll) ▾(oolll)        (oolll → olool) ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# [1/4] + ...
  ▾(oolol)        ▾(oolol)        ▾(oolol)        ▾(oollo)        ▾(oolll)        ▾(oolll)        (oolll → olool) ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# (1/4 1/2) + ...
  (oolol → oolll) (oolol → oolll) (oolol → oolll) ▾(oolll)        ▾(oolll)        ▾(oolll)        (oolll → olool) ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# [1/2] + ...
  ▾(oolll)        ▾(oolll)        ▾(oolll)        ▾(oolll)        ▾(oolll)        ▾(olooo)        ▾(olool)        ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# (1/2 1) + ...
  (oolll → olool) (oolll → olool) (oolll → olool) (oolll → olool) (oolll → olool) ▾(olool)        ▾(olool)        ▾(olool)        (olool → ololl) ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# [1] + ...
  ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(ololo)        ▾(ololl)        ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# (1 2) + ...
  (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) ▾(ololl)        ▾(ololl)        ▾(ololl)        (ololl → ollol) ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# [2] + ...
  ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(olloo)        ▾(ollol)        ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# (2 4) + ...
  (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) ▾(ollol)        ▾(ollol)        ▾(ollol) (ollol → ollll) ▾(ollll) ▾(ollll);
# [4] + ...
  ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(olllo) ▾(ollll)        ▾(ollll) ▾(ollll);
# (4 8) + ...
  (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) ▾(ollll) ▾(ollll)        ▾(ollll) ▾(ollll);
# [8] + ...
  ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll) ▾(ollll)        ▾(ollll) ▾(ollll);
  ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll)        ▾(ollll) ▾(ollll)        ▾(ollll) ▾(ollll);
]
