#5bt-test-sub.jl
#testing an subtraction table for the 5 bit PTile.
#this vector doesn't include negative numbers, or zero or inf (which is trivial)
#note the vector looks like this:
#         [1/8]       [1/4]       [1/2]        [1]         [2]         [4]         [8]
# [00001  00010 00011 00100 00101 00110 00111 01000 01001 01010 01011 01100 01101 01110 01111]

btsub5 = [
#                | [1/8]         |               | [1/4]         |               | [1/2]         |               |  [1]          |               | [2]           |               |   [4]         |               | [8]           |
# (0 1/8) -
  (lllll → ooool) ▾(lllll)        (lllol → lllll) ▾(lllol)        (lloll → lllol) ▾(lloll)        (llool → lloll) ▾(llool)        (lolll → llool) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# [1/8] + ...
  ▾(ooool)        ▾(ooooo)        ▾(lllll)        ▾(llllo)        (lloll → lllol) ▾(lloll)        (llool → lloll) ▾(llool)        (lolll → llool) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# (1/8 1/4) - ...
  (ooool → oooll) ▾(ooool)        (lllll → ooool) ▾(lllll)        (lloll → lllll) ▾(lloll)        (llool → lloll) ▾(llool)        (lolll → llool) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# [1/4] - ...
  ▾(oooll)        ▾(ooolo)        ▾(ooool)        ▾(ooooo)        (lllol → lllll) ▾(llloo)        (llool → lloll) ▾(llool)        (lolll → llool) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# (1/4 1/2) - ...
  (oooll → oolol) (oooll → oolol) (ooool → oolol) (ooool → oooll) (lllol → oooll) (lllol → lllll) (llool → lllll) ▾(llool)        (lolll → llool) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# [1/2] - ...
  ▾(oolol)        ▾(oolol)        ▾(oolol)        ▾(ooloo)        (ooool → oooll) ▾(ooooo)        (lloll → lllll) ▾(llolo)        (lolll → llool) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# (1/2 1) - ...
  (oolol → oolll) (oolol → oolll) (oolol → oolll) (oolol → oolll) (ooool → oolll) (ooool → oolol) (lloll → oolol) (lloll → lllll) (lolll → lllll) ▾(lolll)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# [1] - ...
  ▾(oolll)        ▾(oolll)        ▾(oolll)        ▾(oolll)        ▾(oolll)        ▾(oollo)        (ooool → oolol) ▾(ooooo)        (llool → lllll) ▾(llooo)        (lolol → lolll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# (1 2) - ...
  (oolll → olool) (oolll → olool) (oolll → olool) (oolll → olool) (oolll → olool) (oolll → olool) (ooool → olool) (ooool → oolll) (llool → oolll) (llool → lllll) (lolol → lllll) ▾(lolol)        (looll → lolol) ▾(looll)        (loool → looll);
# [2] - ...
  ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olool)        ▾(olooo)        (ooool → oolll) ▾(ooooo)        (lolll → lllll) ▾(lollo)        (looll → lolol) ▾(looll)        (loool → looll);
# (2 4) - ...
  (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (olool → ololl) (ooool → ololl) (ooool → olool) (lolll → olool) (lolll → lllll) (looll → lllll) ▾(looll)        (loool → looll);
# [4] - ...
  ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololl)        ▾(ololo)        (ooool → olool) ▾(ooooo)        (lolol → lllll) ▾(loloo)        (loool → looll);
# (4 8) - ...
  (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ololl → ollol) (ooool → ollol) (ooool → ololl) (lolol → ololl) (lolol → lllll) (loool → lllll);
# [8] - ...
  ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(ollol)        ▾(olloo)        (ooool → ololl) ▾(ooooo)        (loool → lllll);
# (8 Inf) - ...
  (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ollol → ollll) (ooool → ollll) (ooool → ollll) (loool → ollll);
]
